[workspace]
resolver = "2"
members = [
  "crates/app-runner",
  "crates/db",
  "services/product"
]

[workspace.dependencies]
dotenvy = "0.15"
uuid = { version = "1", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"