[tasks.run-traefik]
workspace = false
description = "Run traefik for local dev"
command = "sh"
args = ["-c", "traefik --config.file=./traefik/traefik.yml --log.level=DEBUG"]

[tasks.run-product]
workspace = false
description = "Run product service"
command = "sh"
args = ["-c", "cargo run -p product"]

[tasks.run-all]
workspace = false
description = "Run product and traefik in background (dev)"
script = [
    "cargo run -p product &",
    "traefik --config.file=./traefik/traefik.yml --log.level=DEBUG &",
    "wait",
]
