[tasks.run-traefik]
workspace = false
description = "Run traefik for local dev (render template then run)"
command = "sh"
args = [
    "-c",
    "[ -f .env ] && . .env || true; cd traefik && ENABLE_DASHBOARD=true ./start-traefik.sh",
]

[tasks.run-product]
workspace = false
description = "Run product service"
command = "sh"
args = [
    "-c",
    "[ -f .env ] && . .env || true; cd services/product && cargo run -p product",
]

[tasks.run-all]
workspace = false
description = "Run product and traefik in background (dev) and stream logs"
command = "sh"
args = ["-c", "[ -f .env ] && . .env || true; ./scripts/run-all.sh"]
