[tasks.run-traefik]
workspace = false
description = "Run traefik for local dev (via start-traefik.sh)"
command = "sh"
args = ["-c", "./traefik/start-traefik.sh"]

[tasks.run-product]
workspace = false
description = "Run product service"
command = "sh"
args = ["-c", "cargo run -p product"]

[tasks.run-all]
workspace = false
description = "Run product and traefik in background (dev)"
script = ["cargo run -p product &", "./traefik/start-traefik.sh &", "wait"]
