api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":8080"
  traefik:
    address: ":8081"

providers:
  file:
    filename: "./dynamic.yml"
    watch: true

log:
  level: DEBUG
