[package]
name = "invent-core"
version = "0.1.0"
edition = "2021"

[dependencies]
axum             = { workspace = true }
tokio            = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = "0.3"
anyhow           = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
uuid             = { workspace = true }
dotenvy          = { workspace = true }
chrono           = { workspace = true }
rust_decimal     = { workspace = true }
jsonwebtoken     = { version = "10.0.0", features = ["rust_crypto"] }
base64           = "0.21.7"
thiserror        = "1"

db         = { path = "../crates/db" }
app-runner = { path = "../crates/app-runner" }
