[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
    "with-chrono",
    "with-rust_decimal",
] }
anyhow       = { workspace = true }
tracing      = { workspace = true }
tokio        = { workspace = true }
uuid         = { workspace = true }
chrono       = { workspace = true }
rust_decimal = { workspace = true }
serde        = { workspace = true }
async-trait  = "0.1"
thiserror    = "1"
